### PR TITLE
trails_meta tests fails

### PR DESCRIPTION
**Pull request by elbrujohalcon**
```
Testing git.cowboy-trails.trails_meta_SUITE: Starting test, 3 test cases

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
dialyzer:check_init failed on line 181
Reason: thrown
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error detected: thrown
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Testing git.cowboy-trails.trails_meta_SUITE: *** FAILED test case 1 of 3 ***

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
elvis_config:validate failed on line 85
Reason: thrown
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error detected: thrown
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Testing git.cowboy-trails.trails_meta_SUITE: *** FAILED test case 2 of 3 ***
Testing git.cowboy-trails.trails_meta_SUITE: TEST COMPLETE, 1 ok, 2 failed of 3 test cases

Cover analysing... done

Updating /home/jean/BA_Projets/git/cowboy-trails/logs/index.html... done
Updating /home/jean/BA_Projets/git/cowboy-trails/logs/all_runs.html... done

erlang.mk:5994 : la recette pour la cible « ct » a échouée
make: *** [ct] Erreur 1
```

### CODE REVIEW

**Comment by jeanparpaillon** [comment]
After running 'make plt-all', tests pass.
Should be added in README.md indeed

**Comment by elbrujohalcon** [comment]
Done :)

**Pull request merged**
